apiVersion: v1
kind: Pod
metadata:
  name: tangpod
  labels:
    name: tangserver
spec:
  containers:
  - name: tangpod
    image: quay.io/melserng/tangpod:v1.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tangservice
    role: service
  name: tangservice
spec:
  ports:
    - port: 76000
      targetPort: 80
      protocol: TCP
      name: tcp
  type: NodePort
  selector:
    name: tangserver
